[package]
name = "mmvc_client"
version = "0.1.0"
edition = "2021"

[dependencies]
ort = "1.16.3"
ndarray = "0.15"
rustfft = "6.2.0"
cpal = "0.15.3"
rubato = "0.15.0"
crossbeam-channel = "0.5.13"
speexdsp-resampler = "0.1.0"
log = "0.4.22"
env_logger = "0.11.5"
anyhow = "1.0.89"
